language: node_js
cache: yarn
node_js:
  - "10"
env:
  - SCRIPT=build
  - SCRIPT=lint
script: yarn run $SCRIPT
stages:
  - name: test
  - name: deploy
    if: tag =~ ^v\d AND type = push

jobs:
  include:
    - stage: test
      env: SCRIPT=jest
      install:
        - yarn --pure-lockfile
      script: yarn run $SCRIPT

    - stage: deploy
      install:
        - npm install -g yarn
        - yarn --pure-lockfile
        - pip install --user awscli
      script:
        - yarn run build
        - yarn pack
        - PACKAGE=`find . -maxdepth 1 -name "*.tgz"`
        - aws s3 cp $PACKAGE s3://$S3_DEFAULT_BUCKET/
      env: ""

install:
  - npm install -g yarn
  - yarn --pure-lockfile
